server {
    listen 8080;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 10485760;

    error_page 404 /404.html;
    error_page 500 /500.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex on;
    }

    location /uploads {
        allow_methods GET POST DELETE;
        upload_path ./www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root ./www;
        cgi_extension .sh;
        cgi_path /usr/bin/bash;
    }
}
