# WebServ Configuration File
# Simple nginx-like configuration

server {
	listen 8080
	listen 8081
	server_name localhost
	client_max_body_size 10485760
	autoindex on
	
	location / root ./www
	location /uploads root ./www/uploads
	
	cgi_extension .py /usr/bin/python3
	cgi_extension .sh /bin/bash
}

server {
	listen 9000
	server_name example.com
	client_max_body_size 1048576
	autoindex off
	
	location / root ./www
	
	cgi_extension .py /usr/bin/python3
}
