server {
    listen 9090;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 1048576;

    error_page 404 /404.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex on;
    }

    location /uploads {
        allow_methods GET POST DELETE;
        upload_path ./www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root ./www;
        cgi_extension .sh;
        cgi_path /usr/bin/bash;
    }
}

server {
    listen 9091;
    server_name test.local;
    root ./www;
    index index.html;

    location / {
        allow_methods GET;
        autoindex on;
    }
}
