server {
    listen 9090;
    server_name localhost;
    root ./www;
    index index.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex on;
    }

    location /uploads {
        allow_methods GET POST DELETE;
        upload_path ./www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root ./www/cgi-bin;
        cgi_extension .py;
    }
}

server {
    listen 9091;
    server_name test.local;
    root ./www;
    index index.html;

    location / {
        allow_methods GET;
        autoindex on;
    }
}