server {
    listen 9199;
    host 0.0.0.0;
    server_name localhost;
    root ./www;
    index index.html;

    location / {
        allow_methods GET POST;
        autoindex off;
    }

    location /uploads {
        allow_methods GET POST;
        upload_path ./www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root ./www/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}
